// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppgacazlfrmifxhhmfhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwZ2FjYXpsZnJtaWZ4aGhtZmhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1ODgzNDksImV4cCI6MjA2NTE2NDM0OX0.c4dUHZ19Rp7_wV5U6gPRMaIf0lfskVyd_zbRXUdNnY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);