// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oywpzlotiryyuafjuwur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95d3B6bG90aXJ5eXVhZmp1d3VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5ODQ3OTAsImV4cCI6MjA2NDU2MDc5MH0.0HK-8jFghnaTemYWQdeB19aE5Ib-gaZu2sW6j_gVb6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);